### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by Horusiath** [y-crdt/y-crdt#241]
Here are some of the initial goals that we'll be surely working on in the first half of 2023:

- [x] **Expose `StickyIndex`/`Offset` API**. *(published in v0.16)*
- [x] **Generic persistence provider API**: while we want to provide a generic interface (that will also make working with subdocuments easier), atm. (Jan 2023) we're still considering options for a proof of concept. We know that there are existing efforts from other independent contributors regarding adding native YRs support inside of [PostgreSQL](https://github.com/supabase/pg_crdt/blob/master/src/y.rs) and SQLite, here we're thinking about:
    - Redis
    - LMDB
    - sled
- [x] **Generic network provider API**: while we have provided a state machine around [y-sync protocol](https://crates.io/crates/y-sync) - which includes Awareness API - and [initial web sockets support](https://crates.io/crates/yrs-warp) of top of Tokio Warp library, here we're most likely try to implement a support over WebRTC.
- [ ] **Gossipping protocol**: update exchange mechanism that works efficiently without requiring every peer to be interconnected with everyone else.
- [ ] **Performance optimizations** - this is a never ending topic, but some ideas would be related to improving block store layout with regard to time necessary to spend to find blocks by ID (which currently seem to be major time factor in many benchmarks).
- [ ] **UI Inspector** capable of displaying and navigating through document store's internal structure - it would be a great help for both debugging and educational purposes.

**Comment by appflowy** [comment]
Hi @Horusiath . I have used sled to implement the persistence layer of the yrs. Can I share this part of the implementation for this task.

**Comment by Horusiath** [comment]
Thanks @appflowy . We created a [generic persistence layer](https://docs.rs/yrs-kvstore/0.1.0/yrs_kvstore/) capable of providing core support for most of the existing persistent key-value stores. We already used in to implement support for [LMDB](https://docs.rs/yrs-lmdb/0.1.0/yrs_lmdb/) and [RocksDB](https://docs.rs/yrs-rocksdb/0.1.0/yrs_rocksdb/) - I think it took <100LOC in each case. I think sled would be no different.

**Comment by appflowy** [comment]
> 

Alright. Cool, the generic layer is really helpful.
