### ISSUE TITLE
Roadmap to v0.19

### ISSUE THREAD

**Issue by Horusiath** [y-crdt/y-crdt#451]
These are features and PRs planned to land on main branch before we release v0.19:
- [x] #438 : make `BranchPtr` and by extension all shared refs, impl `Send` and `Sync`.
- [x]  #449 : new observers API and Awareness (**breaking changes**). 
    - Awareness support in ywasm.
    - Awareness update callback signature goes back to it's old shape prior v0.18: `Fn(&Awareness, &AwarenessEvent) + Send + Sync + 'static`.
    - Awareness now can be generic over type of client state: `Awareness<S>`. That state should be serializable in order to send it beyond process boundaries.
    - While the methods themselves are still compatible with v0.18, the generic function signature changes: now it requires support for `Send` and `Sync` traits for non-wasm targets in order to support calling methods across threads without undefined behaviours (including accidental memory leaks).
- [x] #448 : introduce `Text::apply_delta` method and conversion between `Delta`/`Diff` types.
- [ ] ~~#444 : compile yrs into `rlib` format.~~
- [x] #447 : fix inserting nested types into yffi.
- [x] #450 : fix vulnerabilities in lib0 v2 encoding.
- [x] #460 : new feature flag: `sync` to convert observable callbacks to implement Send+Sync requirements.
- [x] #461 : add ability to freely convert between Value and Prelim types and implement `MapRef::get_or_init` using these features.
- [x] #459 : rename `Value` &rarr; `Out`, introduce `In` which is univeral equivalent for values of any kind but with `Prelim` capabilities. Also Removed generic parameters from prelim types such as `MapPrelim`, `ArrayPrelim`, `TextPrelim` etc.
- [x] #462 : removed mandatory shared ref scope when creating `UndoManager`.
- [x] fixed: lib0 decoding panicing when bufer size was not decoded to valid usize.
- [x] fixed: when encoding document state, pending update was not included as part of an update.
